name: Auto Add Task List Issues

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    # Only run for issues created from task lists
    if: contains(github.event.issue.body, 'Converted from task list item')
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/YOUR_ORG/projects/YOUR_PROJECT_NUMBER
          github-token: ${{ secrets.PROJECT_TOKEN }}