name: Auto Add Task List Issues

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'TASK') || 
      startsWith(github.event.issue.title, 'OKR')
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/BnB3DAO/projects/2
          github-token: ${{ secrets.AUTO_PULL_ISSUES }}
